### ISSUE TITLE
package.json is missing dependencies

### ISSUE THREAD

**Issue by selfrefactor** [Moosylvania/memecanvas#3]
it should be
{
  "name": "memecanvas",
  "version": "1.0.4",
  "description": "Node.js Meme Generator using Node Canvas",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Moosylvania/memecanvas.git"
  },
  "keywords": [
    "meme",
    "canvas",
    "meme",
    "generator",
    "photos",
    "image"
  ],
  "author": {
    "name": "Joe Madden",
    "email": "joe.madden@moosylvania.com"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Moosylvania/memecanvas/issues"
  },
  "homepage": "https://github.com/Moosylvania/memecanvas",
  "dependencies": {
    "canvas": "^1.2.1",
    "async":  "_",
    "colors": "_",
    "mkdirp": "*"
  },
  "gitHead": "641f0814979c7a685bebb627d305b03a00636d40",
  "_id": "memecanvas@1.0.4",
  "_shasum": "cea9093214e2ba5ab05a0b976af0a8997750262d",
  "_from": "memecanvas@",
  "_npmVersion": "2.7.4",
  "_nodeVersion": "0.12.2",
  "_npmUser": {
    "name": "obj63mc",
    "email": "joe.madden@moosylvania.com"
  },
  "maintainers": [
    {
      "name": "obj63mc",
      "email": "joe.madden@moosylvania.com"
    }
  ],
  "dist": {
    "shasum": "cea9093214e2ba5ab05a0b976af0a8997750262d",
    "tarball": "http://registry.npmjs.org/memecanvas/-/memecanvas-1.0.4.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/memecanvas/-/memecanvas-1.0.4.tgz"
}

**Comment by obj63mc** [comment]
This should be all set now and republished.
