### ISSUE TITLE
Can't install memecanvas.

### ISSUE THREAD

**Issue by Tvde1** [Moosylvania/memecanvas#6]
When I try
```
npm i -S memecanvas
```
I get the whole
```
 Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
```
stuff.

I can upload the whole log if you want.

**Comment by obj63mc** [comment]
There are some prerequisites you need installed to be able to install node's canvas module - aka https://github.com/Automattic/node-canvas, checkout - https://github.com/Automattic/node-canvas/wiki and make sure you have followed their recommendations for your OS.  Once you have their prerequisites installed if you can install node canvas by itself you will be okay.
