### ISSUE TITLE
Memecanvas website is dead

### ISSUE THREAD

**Issue by StrangerGithuber** [Moosylvania/memecanvas#7]
Hello
Memecanvas website doesn't work so this api is dead too.
I get this message from website: 
```
Error 1016
Origin DNS error

What happened?

You've requested a page on a website (memecaptain.com) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (memecaptain.com). 
```

**Comment by obj63mc** [comment]
We are not related to that site/api at all, this is a standalone NPM module that lets you build your own memes in your own apps.
